# Generated by Django 3.2.5 on 2022-06-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('minx', models.FloatField()),
                ('maxx', models.FloatField()),
                ('miny', models.FloatField()),
                ('maxy', models.FloatField()),
            ],
        ),
    ]
